name: SchematicSorter
version: ${project.version}
main: com.villaton.schematicsorter.SchematicSorter
api-version: 1.16
authors: [ Villaton ]
softdepend: [ WorldEdit, FastAsyncWorldEdit ]
description: Enhanced schamatic control

commands:
  schems:
    description: Lists all schematics in a folder.